#Sample for settings.yaml

ALARM:
    ALARM 1:
        Start:14:00 #2:00 PM (Mandatory)
        End:14:30 # (Optional, if skipped )
        Frequency:Daily #Everyday (Optinal, default Daily)
#        Frequency:Weekends #Saturday & Sunday
#        Frequency:Weekdays #Monday to Friday
#        Frequency:1111100 #Exact days of the week by 1 and 0's SMTWTFS - here it means Sunday - Thursday and skipping Friday and Saturdays
    Good Morning:
        Start:05:00 
        End:06:00