#Sample for settings.yaml
AVR IP: 192.168.18.2 #IP Address of your AVR
ALARM:
    ALARM 1:
        Start: 14:00 #2:00 PM (Mandatory)
        End:   14:30 # (Optional, if skipped no switch off)
        Frequency:  Daily #Everyday (Optinal, default Daily)
#        Frequency:Weekends #Saturday & Sunday
#        Frequency:Weekdays #Monday to Friday
#        Frequency:1111100 #Exact days of the week by 1 and 0's SMTWTFS - here it means Sunday - Thursday and skipping Friday and Saturdays
    Good Morning:
        Start:  06:00
